services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_BACKEND: ${VITE_BACKEND}
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    build: ./backend
    container_name: backend 
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb

volumes:
  mongo-data: